name: Deploy Discord Bot

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
        
      - name: Update deployment timestamp
        run: |
          # Get current UTC time
          TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M UTC")
          # Replace the placeholder in main.py
          sed -i "s/BOT_LAST_UPDATED = \".*\"/BOT_LAST_UPDATED = \"$TIMESTAMP\"/" main.py
        
      - name: Deploy to server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PASS: ${{ secrets.REMOTE_PASS }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          # Copy the bot file to the server
          export SSHPASS=$REMOTE_PASS
          sshpass -e scp -o StrictHostKeyChecking=no main.py $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/main.py
          
          # Restart the service
          sshpass -e ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl restart discord-bot.service"
          
          # Check service status
          sshpass -e ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo systemctl status discord-bot.service"